---
- name: install with homebrew
  homebrew:
    name: git
    state: latest

- name: add global gitignore
  copy:
    src: gitignore_global
    dest: ~/.gitignore_global

- name: add gitconfig
  template:
    src: files/gitconfig
    dest: ~/.gitconfig
