---
- name: install with cask
  homebrew_cask:
    name: java

# JDK7 is nut available anymore so
# install the zulu OpenJDK 7 build
- name: install Java 7 with cask
  homebrew_cask:
    name: zulu7

- name: install maven with homebrew
  homebrew:
    name: maven
    state: latest

- name: install maven-completion with homebrew
  homebrew:
    name: maven-completion
    state: latest

- name: install sbt with homebrew
  homebrew:
    name: sbt
    state: latest
