---
- name: install with cask
  homebrew_cask:
    name: java

- name: install maven with homebrew
  homebrew:
    name: maven
    state: latest

- name: install maven-completion with homebrew
  homebrew:
    name: maven-completion
    state: latest

- name: install sbt with homebrew
  homebrew:
    name: sbt
    state: latest
