---
- name: install with cask
  homebrew_cask:
    name: java

# JDK7 is nut available anymore so
# install the zulu OpenJDK 7 build
- name: install Java 7 with cask
  homebrew_cask:
    name: zulu7

- name: install Java 6 with cask
  homebrew_cask:
    name: java6

- name: install maven with homebrew
  homebrew:
    name: maven
    state: latest

- name: add mvn config switch script
  copy:
    src: mvn-config/switch.sh
    dest: ~/.m2/switch.sh

- name: install maven-completion with homebrew
  homebrew:
    name: maven-completion
    state: latest

- name: install sbt with homebrew
  homebrew:
    name: sbt
    state: latest
